name: Build & Push Container
description: Build container from Dockerfile and pushes to registry
inputs:
  image_name:
    required: true
    type: string
  registry:
    required: false
    type: string
    default: ghcr.io
  repository_owner:
    required: true
    type: string
  registry_password:
  registry_username:
    required: true
    type: string
  registry_password:
    required: true

env:
  IMAGE_NAME: ${{ inputs.context }}

  IMAGE_REGISTRY: ${{ inputs.registry }}/${{ inputs.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ inputs.registry_username }}
  IMAGE_REGISTRY_PASSWORD: ${{ inputs.registry_password }}

  # Edit to specify custom tags for the container image, or default tags will be generated below
  IMAGE_TAGS: ""
  
outputs:
  image_tag:
    description: "Image Tag"
    value: ${{ steps.values.outputs.image_tag }}
  image_version:
    description: "Image Version"
    value: ${{ steps.values.outputs.image_version }}
  buildtime:
    description: "Build Time"
    value: ${{ steps.values.outputs.buildtime }}

jobs:
  build-push:
    name: Build and push to container registry
    runs-on: ubuntu-18.04
    environment: dev

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
      
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
          ./Dockerfile

    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
   
    - name: Print outputs
      shell: bash
      run: |
        echo "::set-output name=image_tag::${{ fromJSON(steps.meta.outputs.json).tags[0] }}"
        echo "::set-output name=image_version::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
        echo "::set-output name=buildtime::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}"
