name: Build & Push Container
description: Build container from Dockerfile and pushes to registry
inputs:
  context:
    required: true
    type: string
  image_name:
    required: true
    type: string
  ghcr_username:
    required: true
    type: string
  ghcr_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to ghcr container registry
      if: ${{ inputs.ghcr_username != '' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_token }}
        
    - name: Prepare Docker tags for image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ inputs.image_name }}          
        flavor: |
          latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build and push to GHCR
      id: builder
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}