name: Docker CD

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v2
    - name: npm install and build webpack
      run: |
        npm run all:install
        npm run build
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: app/frontend/dist/

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    needs: build
    name: Docker Build, Tag, Push
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub
      uses: docker/login-action@v1 
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        repository: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest