name: Push

env:
  APP_NAME: "vue-scaffold"
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "1dca6b"
  
on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Build
    environment: dev
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'kamorel'
    steps:       
      - uses: actions/checkout@v2
      - name: Build & push container
        id: builder
        uses: ./.github/actions/build-push-container
        with:
          context: './'
          image_name: ${{ github.repository_owner}}/${{ env.APP_NAME }}
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GHCR_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy-dev:
    name: Deploy dev
    environment: dev
    runs-on: ubuntu-18.04
    needs: build    
    if: github.repository_owner == 'kamorel'
    steps: 
    - uses: actions/checkout@v2
    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        # Can we just add the service account to tools namespace
        #   and provide permissions to all namespaces?
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}-dev

    - name: Set outputs
      id: vars
      run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
        
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.SHA_SHORT }}
        
    - name: Update deployment config
      run: |
        oc process -n ${{ env.OPENSHIFT_NAMESPACE }}-dev -f ./openshift/app.dc.yaml -p REPO_NAME=${{ env.APP_NAME }} -p JOB_NAME=master -p NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-dev -p APP_NAME=${{ env.APP_NAME }} -p IMAGE_TAG=${{ env.SHA_SHORT }} -p ROUTE_HOST=${{ env.APP_NAME }}-dev.apps.silver.devops.gov.bc.ca -p ROUTE_PATH=/app -o yaml | oc apply -n ${{ env.OPENSHIFT_NAMESPACE }}-dev -f -
        
  deploy-test:
    name: Deploy test
    environment: test
    runs-on: ubuntu-18.04
    needs: [ build, deploy-dev ]
    if: github.repository_owner == 'kamorel'
    steps: 
    - uses: actions/checkout@v2
    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN_TEST }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}-test

    - name: Set outputs
      id: vars
      run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
        
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.SHA_SHORT }}
        
    - name: Update deployment config
      run: |
        oc process -n ${{ env.OPENSHIFT_NAMESPACE }}-test -f ./openshift/app.dc.yaml -p REPO_NAME=${{ env.APP_NAME }} -p JOB_NAME=master -p NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}-test -p APP_NAME=${{ env.APP_NAME }} -p IMAGE_TAG=${{ env.SHA_SHORT }} -p ROUTE_HOST=${{ env.APP_NAME }}-test.apps.silver.devops.gov.bc.ca -p ROUTE_PATH=/app -o yaml | oc apply -n ${{ env.OPENSHIFT_NAMESPACE }}-test -f -