name: Pull Request Opened

env:
  APP_NAME: "vue-scaffold"
  OPENSHIFT_NAMESPACE: "1dca6b"
  
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:    
      - master
      
jobs:
  build:
    name: Build & Push to Registry
    environment: dev
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kamorel'
    steps:       
      - uses: actions/checkout@v2
      - name: Build & push container
        id: builder
        uses: ./.github/actions/build-push-container
        with:
          context: './'
          image_name: ${{ github.repository_owner}}/${{ env.APP_NAME }}
          ghcr_username: ${{ github.repository_owner}}
          ghcr_password: ${{ secrets.GHCR_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy-pr-dev:
    name: Deploy Pull Request to Dev
    environment: dev
    runs-on: ubuntu-latest
    needs: build    
    if: github.repository_owner == 'kamorel'
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy to Dev
      id: builder
      uses: ./.github/actions/deploy-to-environment
      with:
        openshift_namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        openshift_environment: dev
        app_name: ${{ env.APP_NAME }}
        job_name: pr-${{github.event.number}}
        route_path: /pr-${{github.event.number}}
        openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        