name: Push

env:
  APP_NAME: "vue-scaffold"
  OPENSHIFT_NAMESPACE: "1dca6b"
  
on:
  push:
    types:
      - opened
      - edited
    branches:
      - master
      
jobs:
  build:
    name: Build & Push to Registry
    environment: dev
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'kamorel'
    steps:       
      - uses: actions/checkout@v2
      - name: Build & push container
        id: builder
        uses: ./.github/actions/build-push-container
        with:
          context: './'
          image_name: ${{ github.repository_owner}}/${{ env.APP_NAME }}
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GHCR_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy-dev:
    name: Deploy to Dev
    environment: dev
    runs-on: ubuntu-18.04
    needs: build    
    if: github.repository_owner == 'kamorel'
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy to Dev
      id: builder
      uses: ./.github/actions/deploy-to-environment
      with:
        openshift_namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        openshift_environment: dev
        app_name: ${{ env.APP_NAME }}
        job_name: master
        route_path: /app
        openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        
  deploy-test:
    name: Deploy to Test
    environment: test
    runs-on: ubuntu-18.04
    needs:
      - build
      - deploy-dev
    if: github.repository_owner == 'kamorel'
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy to Test
      id: builder
      uses: ./.github/actions/deploy-to-environment
      with:
        openshift_namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        openshift_environment: test
        app_name: ${{ env.APP_NAME }}
        job_name: master
        route_path: /app
        openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_TEST }}